services:
  - type: web
    name: stock-price-detection
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      PYTHON_VERSION: 3.10.12

